apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    network.host: 0.0.0.0
    cluster.name: "docker-cluster"
    node.name: ${HOSTNAME}