apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gitops
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: feivel123/backend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ELASTICSEARCH_HOST
        - name: ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ELASTICSEARCH_PORT